# https://json.schemastore.org/any.json

root = "../.."
tmp_dir = "backend/cmd/server/tmp"
testdata_dir = "backend/testdata"

[build]
  cmd = "go build -o ./backend/cmd/server/tmp/server.exe ./backend/cmd/server"
  bin = "./backend/cmd/server/tmp/server.exe"
  full_bin = "./backend/cmd/server/tmp/server.exe"

  delay = 1000
  include_ext = ["go", "html", "tmpl", "tpl"]
  exclude_dir = ["backend/cmd/server/tmp", "vendor", "assets", "testdata", "backend/uploads"]
  exclude_regex = ["_test.go"]

  log = "build-errors.log"
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false
  silent = false
  main_only = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
